version: "3"

services:
  redis:
    image: redis:7
    container_name: playhub-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:15
    container_name: playhub-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: playhub
      POSTGRES_USER: playhub
      POSTGRES_PASSWORD: password
