# Generated by Django 5.0.3 on 2024-07-22 14:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Minecraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created",
                        help_text="Date time on which the object was created.",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified",
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(help_text="name of the instance.", max_length=100)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="instance unique identifier.")),
            ],
            options={
                "verbose_name": "Minecraft",
                "verbose_name_plural": "Minecraft",
                "abstract": False,
            },
        ),
    ]
