# Generated by Django 5.0.3 on 2024-07-22 14:13

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("minecraft", "0001_initial"),
        ("network", "0001_initial"),
        ("region", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraft",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="compute", to="network.address"
            ),
        ),
        migrations.AddField(
            model_name="minecraft",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="compute", to="region.region"
            ),
        ),
        migrations.AddField(
            model_name="minecraft",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="minecraft",
            index=models.Index(fields=["uuid"], name="instance_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="minecraft",
            index=models.Index(fields=["region"], name="instance_region_idx"),
        ),
    ]
