# Generated by Django 5.0.3 on 2024-03-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created",
                        help_text="Date time on which the object was created.",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified",
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified",
                    ),
                ),
                ("cidr", models.CharField(help_text="CIDR format network address.", max_length=18)),
                ("ip_address", models.GenericIPAddressField(help_text="IP address for the network.")),
                ("is_disabled", models.BooleanField(default=False, help_text="Flag to disable the network address.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NAT",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created",
                        help_text="Date time on which the object was created.",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified",
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified",
                    ),
                ),
                ("protocol", models.CharField(help_text="Protocol for the NAT rule.", max_length=4)),
                (
                    "dst_port",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Destination port for the NAT rule.", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhiteList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created",
                        help_text="Date time on which the object was created.",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified",
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(
                        blank=True, help_text="Date and time on which the network address was deleted.", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="IP address to be whitelisted.")),
                (
                    "is_disabled",
                    models.BooleanField(default=False, help_text="Flag to disable the whitelisted IP address."),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="whitelist", to="instance.instance"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="whitelist",
            constraint=models.UniqueConstraint(fields=("ip_address", "instance"), name="unique_ip_address_instance"),
        ),
    ]
