# postgres
version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: playhub
      POSTGRES_PASSWORD: playhub
      POSTGRES_DB: playhub
    volumes:
      - playhub:/var/lib/postgresql/data
    container_name: playhub-db

  redis:
    image: redis
    container_name: playhub-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data


volumes:
  playhub:
  redis:
