# Generated by Django 4.2.9 on 2024-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelOptions(
            name="historicalaccounts",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Account",
                "verbose_name_plural": "historical Accounts",
            },
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="historicalaccounts",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="historicalaccounts",
            name="last_name",
        ),
        migrations.AddField(
            model_name="accounts",
            name="name",
            field=models.CharField(
                blank=True, db_column="name", max_length=30, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="historicalaccounts",
            name="name",
            field=models.CharField(
                blank=True, db_column="name", max_length=30, verbose_name="name"
            ),
        ),
    ]
