# Generated by Django 5.0.3 on 2024-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="deleted",
            field=models.DateTimeField(
                blank=True, help_text="Date and time on which the network address was deleted.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalaccounts",
            name="deleted",
            field=models.DateTimeField(
                blank=True, help_text="Date and time on which the network address was deleted.", null=True
            ),
        ),
    ]
