# Generated by Django 4.2.9 on 2024-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accounts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="alias",
            field=models.CharField(
                blank=True,
                db_column="alias",
                max_length=12,
                null=True,
                unique=True,
                verbose_name="alias",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccounts",
            name="alias",
            field=models.CharField(
                blank=True,
                db_column="alias",
                db_index=True,
                max_length=12,
                null=True,
                verbose_name="alias",
            ),
        ),
    ]
