# Generated by Django 5.0.3 on 2024-07-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compute", "0001_initial"),
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamewhitelist",
            name="white_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="game_whitelists", to="network.whitelist"
            ),
        ),
    ]
