"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from os import environ
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from structlog import configure, contextvars, processors, stdlib
from yaml import safe_load

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

DEPLOY_LEVEL = environ.get("DEPLOY_LEVEL", "local").lower()
SETTING_FILE = f"{DEPLOY_LEVEL}.yaml"

with open(f"{BASE_DIR}/config/{SETTING_FILE}", "r") as file:
    cfg = safe_load(file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cfg["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = cfg["DEBUG"]

ALLOWED_HOSTS = cfg["ALLOWED_HOSTS"]
INTERNAL_IPS = cfg["INTERNAL_IPS"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

INSTALLED_LIBRARY_APPS = [
    "storages",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "phonenumber_field",
    "django_structlog",
    "simple_history",
    # "django_celery_beat",
    "django_celery_results",
]

INSTALLED_PROJECT_APPS = [
    # "index",
    "accounts",
    "network",
    "instance",
]

INSTALLED_APPS += INSTALLED_LIBRARY_APPS + INSTALLED_PROJECT_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                # "utility.template.context_processors.toast_tags",
            ],
            "builtins": [
                "utility.template.theme",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = cfg["DATABASES"]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = cfg["LANGUAGE_CODE"]

TIME_ZONE = cfg["TIME_ZONE"]

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static" / "assets"]

MEDIA_URL = "media/"

# STORAGES = cfg["STORAGES"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = cfg["CORS_ALLOWED_ORIGINS"]

AUTH_USER_MODEL = "accounts.Accounts"

SITE_ID = 1

# Allauth
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
AACCOUNT_RATE_LIMITS = {"login_failed": {"count": 5, "period": 300}}
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_ADAPTER = "accounts.adapters.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"
# ACCOUNT_SIGNUP_REDIRECT_URL = ""
LOGIN_REDIRECT_URL = "/"
# ACCOUNT_SIGNUP_REDIRECT_URL = "/accounts/confirm/"

# Session
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_AGE = 60 * 30
SESSION_CACHE_ALIAS = "session"

# Cache
CACHES = cfg["CACHES"]

# LANGUAGES = [
#     ("ko", _("Korean")),
#     ("en", _("English")),
# ]
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("ar", _("Arabic")),
    ("de", _("German")),
    # Add more languages as needed
]

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": stdlib.ProcessorFormatter,
            "processor": processors.JSONRenderer(),
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["require_debug_true"],
        },
        "django": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "when": "midnight",
            "interval": 1,
            "backupCount": 15,
            "filename": BASE_DIR / "logs" / "log.log",
            "formatter": "json",
            "encoding": "utf-8",
            "filters": ["require_debug_false"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "django"],
            "level": "INFO",
        },
    },
}
configure(
    processors=[
        contextvars.merge_contextvars,
        stdlib.filter_by_level,
        processors.TimeStamper(fmt="iso"),
        stdlib.add_logger_name,
        stdlib.add_log_level,
        stdlib.PositionalArgumentsFormatter(),
        processors.StackInfoRenderer(),
        processors.format_exc_info,
        processors.UnicodeDecoder(),
        processors.ExceptionPrettyPrinter(),
        processors.CallsiteParameterAdder(
            {
                processors.CallsiteParameter.PATHNAME,
                processors.CallsiteParameter.FUNC_NAME,
                processors.CallsiteParameter.LINENO,
            }
        ),
        stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

# Email
EMAIL = cfg["EMAIL"]
EMAIL_BACKEND = EMAIL["BACKEND"]
EMAIL_HOST = EMAIL["HOST"]
EMAIL_PORT = EMAIL["PORT"]
EMAIL_HOST_USER = EMAIL["HOST_USER"]
EMAIL_HOST_PASSWORD = EMAIL["HOST_PASSWORD"]
EMAIL_USE_TLS = EMAIL["USE_TLS"]
DEFAULT_FROM_EMAIL = EMAIL["DEFAULT_FROM_EMAIL"]


# Kafka
KAFKA = cfg["KAFKA"]


# Celery
CELERY = cfg["CELERY"]
CELERY_BROKER_URL = CELERY["BROKER_URL"]
CELERY_RESULT_BACKEND = CELERY["RESULT_BACKEND"]
CELERY_TIMEZONE = CELERY["TIMEZONE"]
CELERY_TASK_SERIALIZER = CELERY["TASK_SERIALIZER"]
CELERY_RESULT_SERIALIZER = CELERY["RESULT_SERIALIZER"]
CELERY_TASK_RESULT_EXPIRES = CELERY["TASK_RESULT_EXPIRES"]
CELERY_TASK_SOFT_TIME_LIMIT = CELERY["TASK_SOFT_TIME_LIMIT"]
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = CELERY["BROKER_CONNECTION_RETRY_ON_STARTUP"]
